apiVersion: batch/v1
kind: CronJob
metadata:
  name: recycle
  namespace: uptime-kuma
  labels:
    app: recycle
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: recycle
          serviceAccountName: recycle
          containers:
          - name: recycle
            image: rancherlabs/swiss-army-knife
            imagePullPolicy: IfNotPresent
            command: ["sh", "-c", "/root/bin/recycle.sh" ]
        volumeMounts:
        - mountPath: /root/bin/
          name: script
      volumes:          
      - configMap:
          defaultMode: 493
          name: script
          optional: false
        name: script
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
