apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: recycle
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: recycle
subjects:
- kind: ServiceAccount
  name: recycle
  namespace: uptime-kuma